version: '3'

networks:
  my-network:
    driver: bridge

services:
  mongodb:
    build:
      context: .
      dockerfile: docker/Dockerfile.mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment: # mirror from config.json
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongo-config:/data/config
      - mongo-configdb:/data/configdb
      - mongo-db:/data/db
volumes:
  mongo-config:
    driver: local
  mongo-configdb:
    driver: local
  mongo-db:
    driver: local
    