version: '3'

networks:
  my-network:
    driver: bridge

services:
  mongodb:
    build:
      context: .
      dockerfile: docker/Dockerfile.mongodb
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpass
      MONGO_INITDB_DATABASE: mydatabase
    volumes:
      - mongodb_data:/data/db
volumes:
  mongodb_data:
    driver: local   # Use the local driver for persistent storage
