# Use an official Node.js runtime as a parent image
FROM node:16-alpine3.15

# Set the working directory in the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY frontend/package.json ./

# Install dependencies
RUN npm install

# Copy the source code for the application
COPY frontend/ . 

# Expose port 3000 to the outside world
EXPOSE 3000

# Run the application
CMD ["npm", "start"]
